### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by ttyfly** [Trestrals/crawler_whunews#1]
测试时报错：

```
请输入需要提取的抓取的新闻总数（1～30））
20
请输入排序关键字：time \ source \ title
time
Traceback (most recent call last):
  File ".\crawler.py", line 78, in <module>
    out(msg, val, nowTime)
  File ".\crawler.py", line 13, in out
    fd = os.open(name, os.O_RDWR|os.O_CREAT)
OSError: [Errno 22] Invalid argument: 'output_2020-09-06T00:02:55.json'
```

请查看代码是否有问题。修复后，可直接在这里回复，我会再次查看。

**Comment by Trestrals** [comment]
您好！我在本机测试未发现错误？
<img width="439" alt="截屏2020-09-06 上午12 30 10" src="https://user-images.githubusercontent.com/39334740/92309463-4bafac80-efd8-11ea-854b-f0dba1bd7047.png">

**Comment by Trestrals** [comment]
是否可能是由于系统差异引起的的问题？我再尝试修改一下）

**Comment by Trestrals** [comment]
已修改，不知道现在是否可行？

**Comment by ttyfly** [comment]
> 
> 
> 是否可能是由于系统差异引起的的问题？我再尝试修改一下）

应该的确是系统差异，在 windows 上文件名不能包含“:”。你修改一下文件名格式。

**Comment by Trestrals** [comment]
已修改

**Comment by ttyfly** [comment]
> 
> 
> 已修改

已查看，完成度很高，但仍有一个小问题：输出文件应使用 utf-8 编码。这个应该是打开文件时加一个参数就好了，所以基本可以算是完成了。

感谢参与。后续会公布参考代码和优秀营员名单，敬请关注。

**Comment by Trestrals** [comment]
好的，谢谢指导！
